app/emaskjp/urls.py
from django.urls import path
from . import views

app_name = 'emaskjp'

urlpatterns = [
    path("forms/", views.formview, name="post_new"),
    path("confirm/", views.confirmview, name="post_confirm"),
    path("submit/", views.submitview, name="post_submit"),
    path("thanks/", views.thanksview, name="post_thanks"),
    path("supplyinput/", views.supplyformview, name="supplyinput"),
    path("supplysubmit/", views.supplysubmitview, name="supplysubmit"),
    path("", views.toppageview, name="toppage"),

]

app/reinvent/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("forwarderchat.urls")),
    path("emaskjp/", include("emaskjp.urls")),
]

app/emaskjp/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.


class PrefectureMaster(models.Model):
    # Prefecture Master
    name = models.CharField('Prefecture', max_length=50)


class Entity(models.Model):
    # Legan Entity
    entity_name = models.CharField(
        verbose_name='医療機関名', max_length=200,
        blank=False,
        validators=[MinLengthValidator(2)]
    )
    zip_code = models.CharField(
        verbose_name='zip_code',  # this is displayed in html form
        max_length=8,
        blank=True,
    )
    prefecture = models.CharField(
        verbose_name='都道府県', max_length=40,
        blank=False,
        validators=[MinLengthValidator(3)]
    )
    address1 = models.CharField(
        verbose_name='市区町村番地', max_length=40,
        blank=False,
    )
    address2 = models.CharField(
        verbose_name='建物名', max_length=40,
        blank=True,
    )

    def __str__(self):
        return self.entity_name


class Demand(models.Model):
    entity = models.ForeignKey(
        Entity,
        on_delete=models.CASCADE,)
    begin_date = models.DateField(
        blank=False,
        null=False
    )
    begin_date_display = models.CharField(
        verbose_name='年/月', max_length=40, null=True, blank=True)
    demand_qty = models.DecimalField(max_digits=16, decimal_places=6)

    class Meta:
        unique_together = (('entity', 'begin_date'),)

    def __str__(self):
        return self.begin_date


class Supplier(models.Model):
    name = models.CharField(max_length=200, blank=False,
                            validators=[MinLengthValidator(2)])
    zip_code = models.CharField(
        verbose_name='zip_code',  # this is displayed in html form
        max_length=8,
        blank=True,
    )
    prefecture = models.CharField(
        blank=True, max_length=40, verbose_name='都道府県', )
    address1 = models.CharField(verbose_name='市区町村番地', max_length=40,
                                blank=False,)
    address2 = models.CharField(verbose_name='建物名', max_length=40,
                                blank=True,)


class SupplierContact(models.Model):
    supplier = models.ForeignKey(
        Supplier, null=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True,)
    email = models.EmailField(max_length=200, blank=False)
    phone = PhoneNumberField(blank=True)


class Supply(models.Model):
    destination_entity = models.ForeignKey(
        Entity, on_delete=models.DO_NOTHING,)
    supplier = models.ForeignKey(Supplier, on_delete=models.DO_NOTHING,)
    begin_date = models.DateField(blank=False, null=False)
    supply_qty = models.DecimalField(max_digits=16, decimal_places=6)

    class Meta:
        unique_together = (('destination_entity', 'supplier', 'begin_date'),)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # update of create
        Request, created = Request.objects.update_or_create(
            entity=destination_entity,
            begin_date=begin_date,
        )
        return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    def __str__(self):
        return self.begin_date


class SupplyRequest(models.Model):
    entity = models.ForeignKey(
        Entity, on_delete=models.CASCADE)
    begin_date = models.DateField(blank=False, null=False)
    request_qty = models.DecimalField(max_digits=16, decimal_places=6)
    last_update = models.DateTimeField(
        blank=True, null=True, default=timezone.now)
    last_calculated = models.DateTimeField(
        blank=True, null=True, default=(timezone.datetime.now() - timezone.timedelta(days=1)))
    # When supply created, request created or updated last_update.
    # Every 1 minutes, if last_update > last_calculated or last_update is null,
    # run update().

    class Meta:
        unique_together = (('entity', 'begin_date'),)

app/emaskjp/forms.py
from django import forms
from .models import Entity, Demand, Supplier, SupplierContact, Supply

# reference: https://qiita.com/kk-ster/items/4618dd0a499c2c405b47


class EntityForm(forms.ModelForm):
    class Meta:
        model = Entity
        fields = ['entity_name', 'zip_code',
                  'prefecture', 'address1', 'address2']
        labels = {
            'entity_name': '医療機関名',
            'zip_code': '〒',
        }
        error_messages = {
            'entity_name': {
                'required': '医療機関名を入力してください',
                'min_length': '医療機関名を入力してください'
            },
            'prefecture': {
                'required': '都道府県は必須です',
                'min_length': '郵便番号7桁入力してください'
            },
        }
        widgets = {
            'zip_code':
                forms.TextInput(
                    attrs={'class': 'p-postal-code',
                           'placeholder': '記入例: 8900053'},
                ),
            'prefecture':
                forms.TextInput(
                    attrs={'class': 'p-region', 'placeholder': '記入例: 鹿児島県'},
                ),
            'address1':
                forms.TextInput(
                    attrs={'class': 'p-locality p-street-address p-extended-address',
                           'placeholder': '記入例: 鹿児島市中央町５'},
                ),
            'address2':
                forms.TextInput(
                    attrs={'class': '', 'placeholder': '記入例: 千代田ビル'},
                ),
        }


class DemandForm(forms.ModelForm):
    class Meta:
        model = Demand
        fields = '__all__'
        max_digits = {
            'demand_qty': 6,
        }
        labels = {
            'begin_date': '月',
            'begin_date_display': '年/月',
            'demand_qty': '足りない数',
        }
        error_messages = {
            'demand_qty': {
                'required': '足りない数を入力するか、「0」(=足りている)を入力してください',
                'min_value': '-(マイナス)の数を入力しないでください'
            }
        }
        widgets = {
            'demand_qty':
                forms.NumberInput(
                    attrs={
                        'class': 'p-demand-qty',
                        'placeholder': '記入例: 100',
                    }
                ),
        }


# reference: https://github.com/naritotakizawa/django-inlineformset-sample/blob/master/app/forms.py
DemandFormSet = forms.modelformset_factory(
    Demand,
    form=DemandForm,
    max_num=3,
)


class DemandFormSet3(forms.Form):
    demand0_date = forms.DateField()
    demand1_date = forms.DateField()
    demand2_date = forms.DateField()
    demand0_qty = forms.DecimalField()
    demand1_qty = forms.DecimalField()
    demand2_qty = forms.DecimalField()
    demand0_date_display = forms.CharField()
    demand1_date_display = forms.CharField()
    demand2_date_display = forms.CharField()


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['name', 'zip_code',
                  'prefecture', 'address1', 'address2']
        labels = {
            'name': '送付者のお名前',
            'zip_code': '〒',
            'address1': '市区町村番地',
            'address2': 'マンション名、号室',
        }
        widgets = {
            'zip_code':
                forms.TextInput(
                    attrs={'class': 'p-postal-code',
                           'placeholder': '記入例: 8900053'},
                ),
            'prefecture':
                forms.TextInput(
                    attrs={'class': 'p-region', 'placeholder': '記入例: 鹿児島県'},
                ),
            'address1':
                forms.TextInput(
                    attrs={'class': 'p-locality p-street-address p-extended-address',
                           'placeholder': '記入例: 鹿児島市中央町５'},
                ),
            'address2':
                forms.TextInput(
                    attrs={'class': '', 'placeholder': '記入例: 千代田ビル'},
                ),
        }


class SupplierContactForm(forms.ModelForm):
    class Meta:
        model = SupplierContact
        exclude = ['supplier']


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        exclude = [
            'destination_entity', 'supplier'
        ]

app/emaskjp/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django import db
from django import forms
import datetime

from .models import Entity, Demand, Supply, SupplyRequest
from .forms import EntityForm, DemandForm, DemandFormSet3, SupplierForm, SupplierContactForm, SupplyForm

# Create your views here.

"""
def home(request):
    topDemand = Demand.objects.order_by  # todo: 何をSort基準として表示するのか、考えること
    context = {
        'topDemand': topDemand,
    }
    return render(request, 'emaskjp/home.html', context)
"""


def formview(request):
    # if this is a POST request, we need to process validation of retriving data
    if request.method == 'POST':
        # create a form instance and process retriving data
        receive_form = EntityForm(request.POST)
        is_successful = False
        with db.transaction.atomic():
            if receive_form.is_valid():
                new_entity = receive_form.save(commit=False)

                received3 = DemandFormSet3(request.POST)
            if received3.is_valid():
                demandf1 = DemandForm()
                demand0 = demandf1.save(commit=False)
                demand0.entity = new_entity
                demand0.begin_date = received3.cleaned_data['demand0_date']
                demand0.begin_date_display = received3.cleaned_data['demand0_date_display']
                demand0.demand_qty = received3.cleaned_data['demand0_qty']
                demandf1 = DemandForm()
                demand1 = demandf1.save(commit=False)
                demand1.entity = new_entity
                demand1.begin_date = received3.cleaned_data['demand1_date']
                demand1.begin_date_display = received3.cleaned_data['demand1_date_display']
                demand1.demand_qty = received3.cleaned_data['demand1_qty']
                demandf2 = DemandForm()
                demand2 = demandf2.save(commit=False)
                demand2.entity = new_entity
                demand2.begin_date = received3.cleaned_data['demand2_date']
                demand2.begin_date_display = received3.cleaned_data['demand2_date_display']
                demand2.demand_qty = received3.cleaned_data['demand2_qty']

                srequest0 = SupplyRequest()
                srequest0.entity = new_entity
                srequest0.begin_date = received3.cleaned_data['demand0_date']
                srequest0.request_qty = received3.cleaned_data['demand0_qty']

                valid = new_entity.save()
                valid = demand0.save()
                valid = demand1.save()
                valid = demand2.save()
                valid = srequest0.save()
                is_successful = True

            else:
                is_successful = False

        if is_successful:
            return HttpResponseRedirect('/emaskjp/thanks/')
        else:
            return HttpResponse('Error-55555.')

    else:

        form_class = EntityForm()
        # reference: https://qiita.com/qtatsunishiura/items/a6cc11e025aca1c16ed1

        formset3 = DemandFormSet3(
            initial={
                'demand0_date': datetime.date(year=2020, month=5, day=1),
                'demand0_qty': 0,
                'demand0_date_display': '2020年5月',
                'demand1_date': datetime.date(year=2020, month=6, day=1),
                'demand1_qty': 0,
                'demand1_date_display': '2020年6月',
                'demand2_date': datetime.date(year=2020, month=7, day=1),
                'demand2_qty': 0,
                'demand2_date_display': '2020年7月',
            }
        )
        #    success_url = reverse_lazy('index')
        return render(request, 'emaskjp/inputentity.html', {
            'form': form_class,
            'formset3': formset3,
        })


def confirmview(request):
    demandFormSet = forms.formset_factory(form=DemandForm)
    if request.method == 'POST':
        form = EntityForm(request.POST)
        formset_mask = demandFormSet(request.POST, request.FILES)
        if form.is_valid():
            return render(
                request, 'emaskjp/confirmentity.html', {
                    'form': form,
                    'formset_mask': formset_mask,
                }
            )
        else:
            return render(request, 'emaskjp/inputentity.html', {
                'form': form,
                'formset_mask': formset_mask,
            }
            )
    else:
        new_form = EntityForm()
        demandFormSet = forms.formset_factory(
            form=DemandForm,
            max_num=3
        )          # reference: https://qiita.com/qtatsunishiura/items/a6cc11e025aca1c16ed1

        formset_mask = demandFormSet(
            initial=[
                {
                    'begin_date': datetime.date(year=2020, month=4, day=1),
                    'begin_date_display': '2020年4月',
                    'demand_qty': 0},
                {
                    'begin_date': datetime.date(year=2020, month=5, day=1),
                    'begin_date_display': '2020年5月',
                    'demand_qty': 0},
                {
                    'begin_date': datetime.date(year=2020, month=6, day=1),
                    'begin_date_display': '2020年6月',
                    'demand_qty': 0},
            ]
        )
        return render(request, 'emaskjp/inputentity.html', {
            'form': new_form,
            'formset_mask': formset_mask,
        }
        )


def submitview(request):
    return formview(request)


def thanksview(request):
    return render(request, 'emaskjp/thanks.html')


def supplysubmitview(request):
    return supplyformview(request)

# ここに表示するのは、所要の一覧です。Demandでは無いです。


def supplyformview(request):
    if request.method == 'POST':
        return render(request, 'emaskjp/XXXX.html')
    else:
        form_supply = SupplyForm()
        form_supplier = SupplierForm()
        form_suppliercontact = SupplierContactForm()

        supplyreqs = SupplyRequest.objects.filter(
            request_qty__gt='0').order_by('begin_date', 'last_calculated')[:2]

        return render(
            request,
            'emaskjp/supplyinput.html',
            {
                'form_supply': form_supply,
                'form_supplier': form_supplier,
                'form_suppliercontact': form_suppliercontact,
                'selected_reqs': supplyreqs,
            }
        )

# ここは、最近入力されたSupplyRequest を表示すべきなのは、所要の一覧です。


def toppageview(request):
    queryRequest = SupplyRequest.objects.filter(
        request_qty__gt='0').order_by('begin_date', 'last_calculated')[:5]
    context = {
        'supplyrequest_top': queryRequest,
    }

#    for rrr in queryRequest:
#        print(rrr.entity)
#        print(rrr.entity.entity_name)

    return render(request, 'emaskjp/top.html', context)


def cmdupdate(request):
    SupplyRequest.objects.all()

    context = {
        'item': 'xxx'
    }
    return render(request, 'emaskjp/mgmt_request.html', context)

app/emaskjp/templates/emaskjp/__backup_20200426inputentity.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | 医療機関登録</title>
    <style>
        .p-demand-qty {
            text-align: right;
        }
    </style>
</head>

<body>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <form action="{% url 'emaskjp:post_confirm' %}" method="post" class="h-adr">
        {% csrf_token %}
        <input type="hidden" class="p-country-name" value="Japan">
        <table>
            {{ form.as_table }}
        </table>

        {{ form.non_field_errors }}

        マスクが足りない数を入力してください。
        <table>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>


        </table>
        {{ formset_mask.management_form }}
        <table>
            <tr></tr>
            <tr>
                {% for form_mm in formset_mask %}
                <th>{{ form_mm.begin_date_display.value }}{{ form_mm.begin_date_display.as_hidden }}{{ form_mm.begin_date.as_hidden }}
                </th>
                {% endfor %}
            </tr>
            <tr>
                {% for form_mm in formset_mask %}
                <td>{{ form_mm.demand_qty }}</td>
                {% endfor %}
            </tr>
        </table>
        <input type="submit" value="Submit">
    </form>
</body>

</html>

app/emaskjp/templates/emaskjp/confirmentity.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | 医療機関登録確認</title>
</head>

<table>
    <tr>
        <td>医療機関名:</td>
        <td>{{ form.entity_name.value }}</td>
    </tr>
    <tr>
        <td>郵便番号:</td>
        <td>{{ form.zip_code.value }}</td>
    </tr>
    <tr>
        <td>都道府県:</td>
        <td>{{ form.prefecture.value }}</td>
    </tr>
    <tr>
        <td>市区町村番地:</td>
        <td>{{ form.address1.value }}</td>
    </tr>
    <tr>
        <td>建物名:</td>
        <td>{{ form.address2.value }}</td>
    </tr>
</table>
マスクが足りない数:
<table>
    <tr>
        {% for form_mm in formset_mask %}
        <th>{{ form_mm.begin_date_display.value }}</th>
        {% endfor %}
    </tr>
    <tr>
        {% for form_mm in formset_mask %}
        <td>{{ form_mm.demand_qty.value }}</td>
        {% endfor %}
    </tr>
</table>

<body>
    <form action="{% url 'emaskjp:post_submit' %}" method="post" class="h-adr">
        {% csrf_token %}
        <input type="hidden" class="p-country-name" value="Japan">
        {% for field in form %}
        {{field.as_hidden}}
        {% endfor %}
        {{ formset_mask.management_form }}
        {% for form_mm in formset_mask %}
        {{ form_mm.begin_date_display.as_hidden }}
        {{ form_mm.begin_date.as_hidden }}
        {{ form_mm.demand_qty.as_hidden }}
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
</body>

</html>

app/emaskjp/templates/emaskjp/inputentity.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | 医療機関登録</title>
    <style>
        .p-demand-qty {
            text-align: right;
        }
    </style>
</head>

<body>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <form action="{% url 'emaskjp:post_submit' %}" method="post" class="h-adr">
        {% csrf_token %}
        <input type="hidden" class="p-country-name" value="Japan">
        <table>
            {{ form.as_table }}
        </table>

        {{ form.non_field_errors }}

        マスクが足りない数を入力してください。

        <table>
            <tr></tr>
            <tr>
                <th>{{ formset3.demand0_date_display.value }}
                    {{ formset3.demand0_date_display.as_hidden }}
                    {{ formset3.demand0_date.as_hidden }}
                </th>
                <th>{{ formset3.demand1_date_display.value }}
                    {{ formset3.demand1_date_display.as_hidden }}
                    {{ formset3.demand1_date.as_hidden }}
                </th>
                <th>{{ formset3.demand2_date_display.value }}
                    {{ formset3.demand2_date_display.as_hidden }}
                    {{ formset3.demand2_date.as_hidden }}
                </th>
            </tr>
            <tr>
                <td>{{ formset3.demand0_qty }}</td>
                <td>{{ formset3.demand1_qty }}</td>
                <td>{{ formset3.demand2_qty }}</td>
            </tr>
        </table>
        <input type="submit" value="Submit">
    </form>
</body>

</html>

app/emaskjp/templates/emaskjp/readme.html
Top Page
http://192.168.99.100:8000/emaskjp/

Demand入力
http://192.168.99.100:8000/emaskjp/forms/

Supply 入力
http://192.168.99.100:8000/emaskjp/supplyinput/

所要のUpdate
http://192.168.99.100:8000/emaskjp/supplyinput/

実装したい仕様:
DONE: Top Page で上位5件の病院名を表示。
WIP: Supply 入力して、UpdateRequest(所要の更新)をしたら、所要を更新する。
TODO: Top Page デザイン。Demand 入力とSupply 入力画面につなげる。

参考:
https://qiita.com/okoppe8/items/66a8747cf179a538355b
https://docs.djangoproject.com/ja/3.0/topics/db/queries/
https://codelab.website/django-queryset-filter/
https://noumenon-th.net/programming/2019/11/15/django-listview/
https://www.google.com/search?rlz=1C1SQJL_jaJP869JP869&sxsrf=ALeKk02tvvcbAFmbK-wEtnHuvKGmX1W4qw:1587916693691&q=django+%E4%BA%8C%E9%87%8D%E9%80%81%E4%BF%A1&sa=X&ved=2ahUKEwiu8dbTuobpAhVLFogKHVCpCHQQ1QIoAXoECAsQAg&biw=1113&bih=631
https://qiita.com/hamemi/items/d6cb8e0d60821a7e89aa
https://qiita.com/minnsou/items/db69ab931207ffec66ee
https://www.programcreek.com/python/example/99930/django.db.models.QuerySet
https://qiita.com/zaburo/items/0e15f6c150caa13ca34c#viewspy%E3%82%92%E3%81%84%E3%81%98%E3%82%8B
https://stackoverflow.com/questions/14115318/create-django-model-or-update-if-exists
https://stackoverflow.com/questions/51483763/django-order-by-multiple-fields-and-with-prioritisation
https://qiita.com/Hyperion13fleet/items/1a0369f4f5d523be5870
https://stackoverflow.com/questions/9834038/django-order-by-query-set-ascending-and-descending
https://qiita.com/nisitanisubaru/items/b0c480a3d8b5cf920d44
https://blog-hello-world.web.app/posts/2020-01-12-cloud-datastore-local-docker/
https://qiita.com/komtaki/items/550f02b1eda99a27ccbf


from emaskjp.forms import EntityForm, DemandForm
from emaskjp.models import Entity, Demand
import datetime
import django
from django import forms

new_entity=Entity()
entity_data={
'entity_name': 'kokokoro',
'prefecture': 'ibaraki',
'zip_code': '5600009',
'address1': 'aaa',
'address2': 'bbb',
}
#form=EntityForm(entity_data, instance=new_entity)
form=EntityForm(entity_data)
nnn=form.save(commit=False)
form.is_valid()

DemandFormset = forms.formset_factory(form=DemandForm)

InlineDemandFormsetFactory = forms.inlineformset_factory(
Entity, Demand,
form=DemandForm,
extra=5, max_num=5, can_delete=False
)

#demandFormSet = forms.formset_factory(form=DemandForm)
demand_data={
'entity_name': 'Pkokoko',
'prefecture': 'ibaraki',
'zip_code': '5600009',
'address1': 'aaa',
'address2': 'bbb',
'form-0-begin_date':'2020-04-01',
'form-0-begin_date_display': '2020',
'form-0-demand_qty': 10.0,
'form-INITIAL_FORMS':'1',
'form-MAX_NUM_FORMS':'1',
'form-MIN_NUM_FORMS':'1',
'form-TOTAL_FORMS':'1',
}

formset_demand_mask = InlineDemandFormsetFactory(
demand_data,
instance=nnn
)


-----
from .models import Entity, Demand, Supply, Request, SupplyRequest

all=SupplyRequest.objects.filter(request_qty__gt='0').order_by('last_calculated')
>>> all=SupplyRequest.objects.filter(request_qty__gt='0').order_by('last_calculated')[:5]
>>> all=SupplyRequest.objects.filter(request_qty__gt='0').order_by('begin_date', 'last_calculated')[:5]

app/emaskjp/templates/emaskjp/supplyinput.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | マスク送付予約</title>
    <style>
        .p-demand-qty {
            text-align: right;
        }
    </style>
</head>

<body>
    お届け先:
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
    <form action="{% url 'emaskjp:supplysubmit' %}" method="post" class="h-adr">
        {% csrf_token %}
        <table><input radio id="id_aaa">
            {% for sss in selected_reqs %}
            <tr>
                <td><input type="radio" value="{{ sss.id }}">
                    {{ sss.entity }}
                </td>
            </tr>
            {% endfor %}
        </table>
        送る枚数を教えてください。
        <table>
            {{ form_supply.as_table }}
        </table>
        送付者:
        <table>
            <tr>
                <th><label for="id_country">国</label></th>
                <td><select class="p-country-name" id="id_country">
                        <option value="JP">日本</option>
                        <option value="TW">台湾</option>
                        <option value="CN">中国</option>
                        <option value="VN">ベトナム</option>
                        <option value="TH">タイ</option>
                    </select>
                </td>
            </tr>
            {{ form_supplier.as_table }}
            {{ form_suppliercontact.as_table }}
        </table>
        <input type="date">到着日(defaultは今から3日後になってる)
        送付者(送り元である貴方の住所・連絡先を教えてください。):
        <input type="text">
    </form>
</body>

</html>

app/emaskjp/templates/emaskjp/thanks.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | 登録完了</title>
</head>

<body>
    ありがとうございました。

</body>

</html>

app/emaskjp/templates/emaskjp/top.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title> emask-jp | トップページ</title>
</head>

<body>
    <table>
        {% for ss in supplyrequest_top %}
        <tr>
            <td>
                {{ ss.entity.entity_name }}
            </td>
            <td>
                {{ ss.begin_date }}
            </td>
            <td>
                {{ ss.request_qty }}
            </td>
            <td>
                {{ ss.last_update }}
            </td>
            <td>
                {{ ss.last_calculated }}
            </td>
        </tr>
        {% endfor %}
    </table>
</body>

</html>