app/emaskjp/urls.py
from django.urls import path
from . import views

app_name = 'emaskjp'

urlpatterns = [
    path("forms/", views.formview, name="post_new"),
    path("confirm/", views.confirmview, name="post_confirm"),
    path("submit/", views.submitview, name="post_submit"),
    path("thanks/", views.thanksview, name="post_thanks"),
    path("supplyinput/", views.supplyformview, name="supplyinput"),
    path("supplysubmit/", views.supplysubmitview, name="supplysubmit"),
    path("", views.toppageview, name="toppage"),

]

app/forwarderchat/urls.py
from django.urls import path
from . import views

app_name = 'forwarderchat'

urlpatterns = [
    path("", views.home, name="home"),
    path("listtext/", views.listRFItext, name="listRFItext"),
    path("list/", views.listRFI, name="listRFI"),
    path('detail/<int:RFI_id>/', views.detailRFI, name="detail"),
    path('testforminput/', views.testforminput, name="testforminput"),
    path('inputrfi/', views.inputrfi, name="inputrfi")
]

app/reinvent/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("forwarderchat.urls")),
    path("emaskjp/", include("emaskjp.urls")),
]

app/forwarderchat/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class RFI(models.Model):
    customer_company = models.CharField(max_length=200)
    customer_name = models.CharField(max_length=200)
    customer_prefecture = models.CharField(max_length=50)
    customer_addr = models.CharField(max_length=400)
    create_dt = models.DateTimeField('date created')

    def __str__(self):
        return self.customer_name

    def was_created(self):
        return self.create_dt

app/forwarderchat/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader

from .models import RFI
# Create your views here.


def home(request):
    a = 33
    b = 22
    c = a + b
    return HttpResponse('Hello, Django in Docker!')


def listRFItext(request):
    latest_RFI_list = RFI.objects.order_by('-create_dt')[:5]
    output = ', '.join([r.customer_name for r in latest_RFI_list])
    return HttpResponse(output)


def listRFI(request):
    latest_RFI_list = RFI.objects.order_by('-create_dt')[:5]
    context = {
        'latest_RFI_list': latest_RFI_list,
    }
    return render(request, 'forwarderchat/list.html', context)


def detailRFI(request, RFI_id):
    try:
        rr = RFI.objects.get(pk=RFI_id)
    except RFI.DoesNotExist:
        raise Http404("Something trouble [ERR-50001]")
    return render(request, 'forwarderchat/detail.html', {'RFI': rr})


def testforminput(request):
    error_message = ''
    context = {
        'error_message': error_message,
    }
    return render(request, 'forwarderchat/testforminput.html', context)


def inputrfi(request):
    return render(request, 'forwarderchat/detail.html')

app/forwarderchat/templates/forwarderchat/detail.html
{{ RFI }}<br>
{{ RFI.customer_company }}<br>
{{ RFI.customer_name }}<br>
{{ RFI.customer_addr }}<br>
{{ RFI.customer_prefecture }}<br>
{{ RFI.create_dt }}

app/forwarderchat/templates/forwarderchat/list.html
{% if latest_RFI_list %}
<ul>
    {% for rr in latest_RFI_list %}
    <li><a href="{% url 'forwarderchat:detail' rr.id %}">{{ rr.customer_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No data available</p>
{% endif %}

app/forwarderchat/templates/forwarderchat/testforminput.html
<h1></h1>

{% if error_message %}
<p><strong>{{  error_message }}</strong></p>
{% endif %}

<form action="{% url 'forwarderchat:inputrfi' %}" method="post">
    {% csrf_token %}
    <input type="text" name="customer_company" id="rfi_customer_company" value="">
    <label for="rfi_customer_company">会社名</label><br>
    <input type="text" name="customer_name" id="rfi_customer_name" value="">
    <label for="rfi_customer_name">名前(姓 名)</label><br>
    <input type="text" name="customer_prefecture" id="rfi_customer_prefecture" value="">
    <label for="rfi_customer_prefecture">都道府県</label><br>
    <input type="text" name="customer_addr" id="rfi_customer_addr" value="" size="50">
    <label for="rfi_customer_addr">住所</label><br>
    <input type="submit" value="送信">
</form>